### ISSUE TITLE
The resource template named "Cartography Describe" is already available and is skipped.

### ISSUE THREAD

**Issue by sinanatra** [Daniel-KM/Omeka-S-module-Cartography#8]
Installing the latest release returns this error: 

```
TypeError: Return value of Generic\InstallResources::createResourceTemplate() must be an instance of Omeka\Api\Representation\ResourceTemplateRepresentation, null returned in /Users/giacomonanni/Development/pina-o/modules/Cartography/src/Generic/InstallResources.php:548 Stack trace: #0 /Users/giacomonanni/Development/pina-o/modules/Cartography/src/Generic/InstallResources.php(152): Generic\InstallResources->createResourceTemplate('/Users/giacomon...') #1 /Users/giacomonanni/Development/pina-o/modules/Annotate/src/Generic/AbstractModule.php(164): Generic\InstallResources->createAllResources('Cartography') #2 /Users/giacomonanni/Development/pina-o/modules/Annotate/src/Generic/AbstractModule.php(93): Generic\AbstractModule->installAllResources() #3 /Users/giacomonanni/Development/pina-o/application/src/Module/Manager.php(240): Generic\AbstractModule->install(Object(Laminas\ServiceManager\ServiceManager)) #4 /Users/giacomonanni/Development/pina-o/application/src/Controller/Admin/ModuleController.php(117): Omeka\Module\Manager->install(Object(Omeka\Module\Module)) #5 /Users/giacomonanni/Development/pina-o/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): Omeka\Controller\Admin\ModuleController->installAction() #6 /Users/giacomonanni/Development/pina-o/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent)) #7 /Users/giacomonanni/Development/pina-o/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure)) #8 /Users/giacomonanni/Development/pina-o/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent)) #9 /Users/giacomonanni/Development/pina-o/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response)) #10 /Users/giacomonanni/Development/pina-o/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent)) #11 /Users/giacomonanni/Development/pina-o/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure)) #12 /Users/giacomonanni/Development/pina-o/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent)) #13 /Users/giacomonanni/Development/pina-o/index.php(21): Laminas\Mvc\Application->run() #14 {main}
```

**Comment by Daniel-KM** [comment]
This issue is fixed in version 3.4.4.
