### ISSUE TITLE
TypeError: Return value of Generic\InstallResources::createResourceTemplate() must be an instance of Omeka\Api\Representation\ResourceTemplateRepresentation

### ISSUE THREAD

**Issue by sinanatra** [Daniel-KM/Omeka-S-module-Cartography#9]
When i try to install the module on Omeka S version 3.2.1 i receive the following error:

```
TypeError: Return value of Generic\InstallResources::createResourceTemplate() must be an instance of Omeka\Api\Representation\ResourceTemplateRepresentation, null returned in /home/project/omeka-s/modules/Cartography/src/Generic/InstallResources.php:548
Stack trace:
#0 /home/project/omeka-s/modules/Cartography/src/Generic/InstallResources.php(152): Generic\InstallResources->createResourceTemplate()
#1 /home/project/omeka-s/modules/Generic/AbstractModule.php(178): Generic\InstallResources->createAllResources()
#2 /home/project/omeka-s/modules/Generic/AbstractModule.php(107): Generic\AbstractModule->installAllResources()
#3 /home/project/omeka-s/application/src/Module/Manager.php(240): Generic\AbstractModule->install()
#4 /home/project/omeka-s/application/src/Controller/Admin/ModuleController.php(117): Omeka\Module\Manager->install()
#5 /home/project/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): Omeka\Controller\Admin\ModuleController->installAction()
#6 /home/project/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch()
#7 /home/project/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#8 /home/project/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil()
#9 /home/project/omeka-s/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch()
#10 /home/project/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch()
#11 /home/project/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#12 /home/project/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil()
#13 /home/project/omeka-s/index.php(21): Laminas\Mvc\Application->run()
#14 {main}
```

**Comment by Daniel-KM** [comment]
This issue is fixed in version 3.4.4.
